server:  servlet:    context-path: /portal
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/education_portal
    username: root
    password: root
    hikari:      data-source-properties:        useSSL: false
        createDatabaseIfNotExist: true	        
  jpa:    hibernate:      ddl-auto: update
    show-sql: true
    open-in-view: false  