server:  servlet:    context-path: /portal
spring:
  portal:     datasource:
       url: jdbc:mysql://localhost:3306/education_portal
       username: root
       password: root       #Since Spring boot 2, the schema is only initialized by default for embedded datasources.        #To allow loading data for all types of datasources, you have to set the following property:       #initialization-mode: ALWAYS
       hikari:         data-source-properties:           useSSL: false
           createDatabaseIfNotExist: true     course:     datasource:       url: jdbc:mysql://localhost:3306/video_portal       username: root       password: root       #initialization-mode: ALWAYS       hikari:         data-source-properties:           useSSL: false           createDatabaseIfNotExist: true 
  jpa:    show-sql: true
    open-in-view: false