INSERT IGNORE INTO `country` (`name`,`phone_code`,`short_name`) VALUES ('India',91,'IN'),('United States',1,'US');

INSERT IGNORE INTO `state` (`name`,`country_id`) VALUES ('Andaman & Nicobar Islands',1),('Andhra Pradesh',1),('Arunachal Pradesh',1),('Assam',1),('Bihar',1),('Chandigarh',1),('Chattisgarh',1),('Dadra & Nagar Haveli',1),('Daman & Diu',1),('Delhi',1),('Goa',1),('Gujarat',1),('Haryana',1),('Himachal Pradesh',1),('Jammu & Kashmir',1),('Jharkhand',1),('Karnataka',1),('Kerala',1),('Lakshadweep',1),('Madhya Pradesh',1),('Maharashtra',1),('Manipur',1),('Meghalaya',1),('Mizoram',1),('Nagaland',1),('Odisha',1),('Poducherry',1),('Punjab',1),('Rajasthan',1),('Sikkim',1),('Tamil Nadu',1),('Telangana',1),('Tripura',1),('Uttar Pradesh',1),('Uttarakhand',1),('West Bengal',1);

INSERT IGNORE INTO `city` (`name`,`state_id`) VALUES 
("Adilabad",32),
("Agra",34),
("Ahmed Nagar",21),
("Ahmedabad City",12),
("Aizawl",24),
("Ajmer",29),
("Akola",21),
("Aligarh",34),
("Allahabad",34),
("Alleppey",18),
("Almora",35),
("Alwar",29),
("Alwaye",18),
("Amalapuram",2),
("Ambala",13),
("Ambedkar Nagar",34),
("Amravati",21),
("Amreli",12),
("Amritsar",28),
("Anakapalle",2),
("Anand",12),
("Anantapur",2),
("Ananthnag",15),
("Anna Road H.O",31),
("Arakkonam",31),
("Asansol",36),
("Aska",26),
("Auraiya",34),
("Aurangabad",21),
("Aurangabad(Bihar)",5),
("Azamgarh",34),
("Bagalkot",17),
("Bageshwar",35),
("Bagpat",34),
("Bahraich",34),
("Balaghat",20),
("Balangir",26),
("Balasore",26),
("Ballia",34),
("Balrampur",34),
("Banasanktha",12),
("Banda",34),
("Bandipur",15),
("Bankura",36),
("Banswara",29),
("Barabanki",34),
("Baramulla",15),
("Baran",29),
("Bardoli",12),
("Bareilly",34),
("Barmer",29),
("Barnala",28),
("Barpeta",4),
("Bastar",7),
("Basti",34),
("Bathinda",28),
("Beed",21),
("Begusarai",5),
("Belgaum",17),
("Bellary",17),
("Bengaluru East",17),
("Bengaluru South",17),
("Bengaluru West",17),
("Berhampur",26),
("Bhadrak",26),
("Bhagalpur",5),
("Bhandara",21),
("Bharatpur",29),
("Bharuch",12),
("Bhavnagar",12),
("Bhilwara",29),
("Bhimavaram",2),
("Bhiwani",13),
("Bhojpur",5),
("Bhopal",20),
("Bhubaneswar",26),
("Bidar",17),
("Bijapur",17),
("Bijnor",34),
("Bikaner",29),
("Bilaspur",7),
("Birbhum",36),
("Bishnupur",22),
("Bongaigaon",4),
("Budaun",34),
("Budgam",15),
("Bulandshahr",34),
("Buldhana",21),
("Bundi",29),
("Burdwan",36),
("Cachar",4),
("Calicut",18),
("Carnicobar",1),
("Chamba",14),
("Chamoli",35),
("Champawat",35),
("Champhai",24),
("Chandauli",34),
("Chandel",22),
("Chandigarh",6),
("Chandrapur",21),
("Changanacherry",18),
("Changlang",3),
("Channapatna",17),
("Chengalpattu",31),
("Chennai City Central",31),
("Chennai City North",31),
("Chennai City South",31),
("Chhatarpur",20),
("Chhindwara",20),
("Chikmagalur",17),
("Chikodi",17),
("Chitradurga",17),
("Chitrakoot",34),
("Chittoor",2),
("Chittorgarh",29),
("Churachandpur",22),
("Churu",29),
("Coimbatore",31),
("Contai",36),
("Cooch Behar",36),
("Cuddalore",31),
("Cuddapah",2),
("Cuttack City",26),
("Cuttack North",26),
("Cuttack South",26),
("Dadra & Nagar Haveli",8),
("Daman",9),
("Darbhanga",5),
("Darjiling",36),
("Darrang",4),
("Dausa",29),
("Dehra Gopipur",14),
("Dehradun",35),
("Delhi",10),
("Deoria",34),
("Dhalai",33),
("Dhanbad",16),
("Dharamsala",14),
("Dharmapuri",31),
("Dharwad",17),
("Dhemaji",4),
("Dhenkanal",26),
("Dholpur",29),
("Dhubri",4),
("Dhule",21),
("Dibang Valley",3),
("Dibrugarh",4),
("Diglipur",1),
("Dimapur",25),
("Dindigul",31),
("Diu",9),
("Doda",15),
("Dungarpur",29),
("Durg",7),
("East Champaran",5),
("East Garo Hills",23),
("East Kameng",3),
("East Khasi Hills",23),
("East Siang",3),
("East Sikkim",30),
("Eluru",2),
("Ernakulam",18),
("Erode",31),
("Etah",34),
("Etawah",34),
("Faizabad",34),
("Faridabad",13),
("Faridkot",28),
("Farrukhabad",34),
("Fatehgarh Sahib",28),
("Fatehpur",34),
("Fazilka",28),
("Ferrargunj",1),
("Firozabad",34),
("Firozpur",28),
("Gadag",17),
("Gadchiroli",21),
("Gandhinagar",12),
("Ganganagar",29),
("Gautam Buddha Nagar",34),
("Gaya",5),
("Ghaziabad",34),
("Ghazipur",34),
("Giridih",16),
("Goa",11),
("Goalpara",4),
("Gokak",17),
("Golaghat",4),
("Gonda",34),
("Gondal",12),
("Gondia",21),
("Gorakhpur",34),
("Gudivada",2),
("Gudur",2),
("Gulbarga",17),
("Guna",20),
("Guntur",2),
("Gurdaspur",28),
("Gurugram",13),
("Gwalior",20),
("Hailakandi",4),
("Hamirpur (HP)",14),
("Hamirpur (UP)",34),
("Hanamkonda",32),
("Hanumangarh",29),
("Hardoi",34),
("Haridwar",35),
("Hassan",17),
("Hathras",34),
("Haveri",17),
("Hazaribagh",16),
("Hindupur",2),
("Hingoli",21),
("Hissar",13),
("Hooghly",36),
("Hoshangabad",20),
("Hoshiarpur",28),
("Howrah",36),
("Hut Bay",1),
("Hyderabad City",32),
("Hyderabad South East",32),
("Idukki",18),
("Imphal East",22),
("Imphal West",22),
("Indore City",20),
("Indore Moffusil",20),
("Irinjalakuda",18),
("Jabalpur",20),
("Jaintia Hills",23),
("Jaipur",29),
("Jaisalmer",29),
("Jalandhar",28),
("Jalaun",34),
("Jalgaon",21),
("Jalna",21),
("Jalor",29),
("Jalpaiguri",36),
("Jammu",15),
("Jamnagar",12),
("Jaunpur",34),
("Jhalawar",29),
("Jhansi",34),
("Jhujhunu",29),
("Jodhpur",29),
("Jorhat",4),
("Junagadh",12),
("Jyotiba Phule Nagar",34),
("Kakinada",2),
("Kalahandi",26),
("Kamrup",4),
("Kanchipuram",31),
("Kannauj",34),
("Kanniyakumari",31),
("Kannur",18),
("Kanpur Dehat",34),
("Kanpur Nagar",34),
("Kapurthala",28),
("Karaikal",27),
("Karaikudi",31),
("Karauli",29),
("Karbi Anglong",4),
("Kargil",15),
("Karimganj",4),
("Karimnagar",32),
("Karnal",13),
("Karur",31),
("Karwar",17),
("Kasaragod",18),
("Kathua",15),
("Kaushambi",34),
("Keonjhar",26),
("Khammam (AP)",2),
("Khammam (TL)",32),
("Khandwa",20),
("Kheda",12),
("Kheri",34),
("Kiphire",25),
("Kodagu",17),
("Kohima",25),
("Kokrajhar",4),
("Kolar",17),
("Kolasib",24),
("Kolhapur",21),
("Kolkata",36),
("Koraput",26),
("Kota",29),
("Kottayam",18),
("Kovilpatti",31),
("Krishnagiri",31),
("Kulgam",15),
("Kumbakonam",31),
("Kupwara",15),
("Kurnool",2),
("Kurukshetra",13),
("Kurung Kumey",3),
("Kushinagar",34),
("Kutch",12),
("Lakhimpur",4),
("Lakshadweep",19),
("Lalitpur",34),
("Latur",21),
("Lawngtlai",24),
("Leh",15),
("Lohit",3),
("Longleng",25),
("Lower Subansiri",3),
("Lucknow",34),
("Ludhiana",28),
("Lunglei",24),
("Machilipatnam",2),
("Madhubani",5),
("Madurai",31),
("Mahabubnagar",32),
("Maharajganj",34),
("Mahesana",12),
("Mahoba",34),
("Mainpuri",34),
("Malda",36),
("Mammit",24),
("Mandi",14),
("Mandsaur",20),
("Mandya",17),
("Mangalore",17),
("Manjeri",18),
("Mansa",28),
("Marigaon",4),
("Mathura",34),
("Mau",34),
("Mavelikara",18),
("Mayabander",1),
("Mayiladuthurai",31),
("Mayurbhanj",26),
("Medak",32),
("Meerut",34),
("Meghalaya",23),
("Midnapore",36),
("Mirzapur",34),
("Moga",28),
("Mohali",28),
("Mokokchung",25),
("Mon",25),
("Monghyr",5),
("Moradabad",34),
("Morena",20),
("Muktsar",28),
("Mumbai",21),
("Murshidabad",36),
("Muzaffarnagar",34),
("Muzaffarpur",5),
("Mysore",17),
("Nadia",36),
("Nagaon",4),
("Nagapattinam",31),
("Nagaur",29),
("Nagpur",21),
("Nainital",35),
("Nalanda",5),
("Nalbari",4),
("Nalgonda",32),
("Namakkal",31),
("Nancorie",1),
("Nancowrie",1),
("Nanded",21),
("Nandurbar",21),
("Nandyal",2),
("Nanjangud",17),
("Narasaraopet",2),
("Nashik",21),
("Navsari",12),
("Nawadha",5),
("Nawanshahr",28),
("Nellore",2),
("Nilgiris",31),
("Nizamabad",32),
("North 24 Parganas",36),
("North Cachar Hills",4),
("North Dinajpur",36),
("North Sikkim",30),
("North Tripura",33),
("Osmanabad",21),
("Ottapalam",18),
("Palamau",16),
("Palghat",18),
("Pali",29),
("Panchmahals",12),
("Papum Pare",3),
("Parbhani",21),
("Parvathipuram",2),
("Patan",12),
("Pathanamthitta",18),
("Patiala",28),
("Patna",5),
("Pattukottai",31),
("Pauri Garhwal",35),
("Peddapalli",32),
("Peren",25),
("Phek",25),
("Phulbani",26),
("Pilibhit",34),
("Pithoragarh",35),
("Poducherry (PD)",27),
("Poducherry (TN)",31),
("Pollachi",31),
("Poonch",15),
("Porbandar",12),
("Port Blair",1),
("Prakasam",2),
("Pratapgarh",34),
("Proddatur",2),
("Pudukkottai",31),
("Pulwama",15),
("Pune",21),
("Puri",26),
("Purnea",5),
("Purulia",36),
("Puttur",17),
("Quilon",18),
("Raebareli",34),
("Raichur",17),
("Raigarh (CT)",7),
("Raigarh (MH)",21),
("Raipur",7),
("Rajahmundry",2),
("Rajauri",15),
("Rajkot",12),
("Rajsamand",29),
("Ramanathapuram",31),
("Rampur",34),
("Rampur Bushahr",14),
("Ranchi",16),
("Rangat",1),
("Ratlam",20),
("Ratnagiri",21),
("Reasi",15),
("Rewa",20),
("Ri Bhoi",23),
("Rohtak",13),
("Rohtas",5),
("Ropar",28),
("Rudraprayag",35),
("Rupnagar",28),
("Sabarkantha",12),
("Sagar",20),
("Saharanpur",34),
("Saharsa",5),
("Salem East",31),
("Salem West",31),
("Samastipur",5),
("Sambalpur",26),
("Sangareddy",32),
("Sangli",21),
("Sangrur",28),
("Sant Kabir Nagar",34),
("Sant Ravidas Nagar",34),
("Santhal Parganas",16),
("Saran",5),
("Satara",21),
("Sawai Madhopur",29),
("Secunderabad",32),
("Sehore",20),
("Senapati",22),
("Serchhip",24),
("Shahdol",20),
("Shahjahanpur",34),
("Shimla",14),
("Shimoga",17),
("Shrawasti",34),
("Sibsagar",4),
("Siddharthnagar",34),
("Sikar",29),
("Sindhudurg",21),
("Singhbhum",16),
("Sirohi",29),
("Sirsi",17),
("Sitamarhi",5),
("Sitapur",34),
("Sivaganga",31),
("Siwan",5),
("Solan",14),
("Solapur",21),
("Sonbhadra",34),
("Sonepat",13),
("Sonitpur",4),
("South 24 Parganas",36),
("South Dinajpur",36),
("South Garo Hills",23),
("South Sikkim",30),
("South Tripura",33),
("Srikakulam",2),
("Srinagar",15),
("Srirangam",31),
("Sultanpur",34),
("Sundargarh",26),
("Surat",12),
("Surendranagar",12),
("Suryapet",32),
("Tadepalligudem",2),
("Tambaram",31),
("Tamenglong",22),
("Tamluk",36),
("Tarn Taran",28),
("Tawang",3),
("Tehri Garhwal",35),
("Tenali",2),
("Thalassery",18),
("Thane",21),
("Thanjavur",31),
("Theni",31),
("Thoubal",22),
("Tinsukia",4),
("Tirap",3),
("Tiruchirapalli",31),
("Tirunelveli",31),
("Tirupati",2),
("Tirupattur",31),
("Tirupur",31),
("Tirur",18),
("Tiruvalla",18),
("Tiruvannamalai",31),
("Tonk",29),
("Trichur",18),
("Trivandrum North",18),
("Trivandrum South",18),
("Tuensang",25),
("Tumkur",17),
("Tuticorin",31),
("Udaipur",29),
("Udham Singh Nagar",35),
("Udhampur",15),
("Udupi",17),
("Ujjain",20),
("Ukhrul",22),
("Una",14),
("Unnao",34),
("Upper Siang",3),
("Upper Subansiri",3),
("Uttarkashi",35),
("Vadakara",18),
("Vadodara East",12),
("Vadodara West",12),
("Vaishali",5),
("Valsad",12),
("Varanasi",34),
("Vellore",31),
("Vidisha",20),
("Vijayawada",2),
("Virudhunagar",31),
("Visakhapatnam",2),
("Vizianagaram",2),
("Vriddhachalam",31),
("Wanaparthy",32),
("Warangal",32),
("Wardha",21),
("Washim",21),
("West Champaran",5),
("West Garo Hills",23),
("West Kameng",3),
("West Khasi Hills",23),
("West Siang",3),
("West Sikkim",30),
("West Tripura",33),
("Wokha",25),
("Yavatmal",21),
("Zunhebotto",25);